apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-abc
  name: nginx-abc
  namespace: nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-abc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-abc
    spec:
      serviceAccountName: nginx
      containers:
      - image: nginxinc/nginx-unprivileged
        imagePullPolicy: Always
        name: nginx
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: nginx-storage
            mountPath: /var/log/nginx
        securityContext:
          runAsNonRoot: true
          # runAsUser: 2016
          # runAsGroup: 2016
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
      # dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

# kubectl get pod nginx-abc2 -o jsonpath='{.status.hostIP}'
# http://<ip address of node>:30080/
# http://10.20.1.23:30080/


